version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: asdf1234
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    image: cc:1.0  
    container_name: my-web-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
